server:
  port: ${PORT}

login:
  email: ${LOGIN_EMAIL}
  password: ${LOGIN_PASSWORD}

spring:
  flyway:
    locations: classpath:/db/migration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}